package units:module;

interface driver {
    intend: func(input: string) -> string;
    done: func(input: string);
    transfer: func(fro: string, to: string, value: string);
    view: func(input: string) -> string;
}

world module {
    import driver;
    export main: func(input: string) -> string;
}
